export const enquiryLangugeData = [
    {
      id: 1,
      language: "hindi",
      videoUrl: require("../localdata/localdata"),
      name: "आपका नाम (Full Name)",
      country: "देश (Country)",
      whatsappNumber: "आपका मोबाइल नंबर (WhatsApp Phone Number)",
      businessType: "आप किस तरह का बिज़नेस करते हो (Business Type)",
      smallshop: "छोटी दुकान है (Small Shop)",
      Wholesaler: "होलसेलर (Wholesaler)",
      NewBusiness: "नया बिज़नेस (New Business)",
      Message: "कोई और वजह हमे संपर्क करने के लिए (Message)",
      Submit: "जमा करें",
    },
    {
      id: 2,
      language: "english",
      videoUrl: require("../localdata/localdata"),
      name: "Full Name",
      country: "Country",
      whatsappNumber: "WhatsApp Phone Number",
      businessType: "What type of business do you do?",
      smallshop: "Small Shop",
      Wholesaler: "Wholesaler",
      NewBusiness: "New Business",
      Message: "Any other reason to contact us (Message)",
      Submit: "Submit",
    },
    {
      id: 3,
      language: "telugu",
      videoUrl: require("../localdata/localdata"),
      name: "మీ పేరు (Full Name)",
      country: "దేశం (Country)",
      whatsappNumber: "మీ మొబైల్ నంబర్ (WhatsApp Phone Number)",
      businessType: "మీరు ఏ రకమైన వ్యాపారం చేస్తున్నారు? (Business Type)",
      smallshop: "చిన్న దుకాణం ఉంది (Small Shop)",
      Wholesaler: "హోల్సేలర్ (Wholesaler)",
      NewBusiness: "కొత్త వ్యాపారం (New Business)",
      Message: "మమ్మల్ని సంప్రదించడానికి మరేదైనా కారణం (Message)",
      Submit: "సబ్మిట్ చేయండి",
    },
    {
      id: 4,
      language: "tamil1",
      videoUrl: require("../localdata/localdata"),
      name: "உங்கள் பெயர் (Full Name)",
      country: "நாடு (Country)",
      whatsappNumber: "உங்கள் மொபைல் எண் (WhatsApp Phone Number)",
      businessType: "நீங்கள் எவ்வாறு வியாபாரம் செய்கிறீர்கள்? (Business Type)",
      smallshop: "சிறிய கடை உள்ளது (Small Shop)",
      Wholesaler: "மொத்த வியாபாரி (Wholesaler)",
      NewBusiness: "புதிய வியாபாரம் (New Business)",
      Message: "மற்றவொரு காரணம் (Message)",
      Submit: "சமர்ப்பிக்கவும்",
    },
    {
      id: 5,
      language: "tamil2",
      videoUrl: require("../localdata/localdata"),
      name: "உங்களின் முழுப் பெயர் (Full Name)",
      country: "நாடு (Country)",
      whatsappNumber: "உங்கள் வாட்ஸ்ஆப் எண் (WhatsApp Phone Number)",
      businessType:
        "நீங்கள் எப்படிப்பட்ட வணிகத்தை செய்கிறீர்கள்? (Business Type)",
      smallshop: "சிறிய கடை (Small Shop)",
      Wholesaler: "மொத்த வியாபாரி (Wholesaler)",
      NewBusiness: "புதிய வணிகம் (New Business)",
      Message: "மற்ற காரணம் தொடர்புக்கு (Message)",
      Submit: "சமர்ப்பிக்கவும்",
    },
    {
      id: 6,
      language: "kannada",
      videoUrl: require("../localdata/localdata"),
      name: "ನಿಮ್ಮ ಹೆಸರು (Full Name)",
      country: "ದೇಶ (Country)",
      whatsappNumber: "ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ (WhatsApp Phone Number)",
      businessType: "ನೀವು ಯಾವ ರೀತಿ ವ್ಯಾಪಾರ ಮಾಡುತ್ತೀರಾ? (Business Type)",
      smallshop: "ಚಿಕ್ಕ ಅಂಗಡಿ (Small Shop)",
      Wholesaler: "ಹೊಲ್ಸೇಲರ್ (Wholesaler)",
      NewBusiness: "ಹೊಸ ವ್ಯಾಪಾರ (New Business)",
      Message: "ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಲು ಬೇರೆ ಕಾರಣ (Message)",
      Submit: "ಸಲ್ಲಿಸು",
    },
    {
      id: 7,
      language: "malayalam",
      videoUrl: require("../localdata/localdata"),
      name: "നിങ്ങളുടെ പേര് (Full Name)",
      country: "രാജ്യം (Country)",
      whatsappNumber: "നിങ്ങളുടെ മൊബൈൽ നമ്പർ (WhatsApp Phone Number)",
      businessType: "താങ്കൾ എന്ത് ബിസിനസ് ചെയ്യുന്നു? (Business Type)",
      smallshop: "ചെറിയ കട (Small Shop)",
      Wholesaler: "ഹോൾസെയ്ലർ (Wholesaler)",
      NewBusiness: "പുതിയ ബിസിനസ് (New Business)",
      Message: "മറ്റു കാരണങ്ങൾ (Message)",
      Submit: "സമർപ്പിക്കുക",
    },
    {
      id: 8,
      language: "marathi",
      videoUrl: require("../localdata/localdata"),
      name: "तुमचे नाव (Full Name)",
      country: "देश (Country)",
      whatsappNumber: "तुमचा मोबाईल क्रमांक (WhatsApp Phone Number)",
      businessType: "तुम्ही कोणता व्यवसाय करता? (Business Type)",
      smallshop: "छोटे दुकान आहे (Small Shop)",
      Wholesaler: "होलसेलर (Wholesaler)",
      NewBusiness: "नवीन व्यवसाय (New Business)",
      Message: "आमच्याशी संपर्क साधण्याचे अन्य कारण (Message)",
      Submit: "सबमिट",
    },
    {
      id: 9,
      language: "bengali",
      videoUrl: require("../localdata/localdata"),
      name: "আপনার নাম (Full Name)",
      country: "দেশ (Country)",
      whatsappNumber: "আপনার মোবাইল নম্বর (WhatsApp Phone Number)",
      businessType: "আপনি কী ধরনের ব্যবসা করেন? (Business Type)",
      smallshop: "ছোট দোকান (Small Shop)",
      Wholesaler: "হোলসেলার (Wholesaler)",
      NewBusiness: "নতুন ব্যবসা (New Business)",
      Message: "আমাদের সাথে যোগাযোগ করার অন্য কোনো কারণ (Message)",
      Submit: "জমা দিন",
    },
    {
      id: 10,
      language: "gujarati",
      videoUrl: require("../localdata/localdata"),
      name: "તમારું નામ (Full Name)",
      country: "દેશ (Country)",
      whatsappNumber: "તમારો મોબાઇલ નંબર (WhatsApp Phone Number)",
      businessType: "તમે કયો વ્યવસાય કરો છો? (Business Type)",
      smallshop: "નાનું દુકાન (Small Shop)",
      Wholesaler: "થોક વેપારી (Wholesaler)",
      NewBusiness: "નવો વ્યવસાય (New Business)",
      Message: "અમારો સંપર્ક કરવા માટે બીજું કારણ (Message)",
      Submit: "સબમિટ કરો",
    },
    {
      id: 11,
      language: "odia",
      videoUrl: require("../localdata/localdata"),
      name: "ଆପଣଙ୍କର ନାମ (Full Name)",
      country: "ଦେଶ (Country)",
      whatsappNumber: "ଆପଣଙ୍କର ମୋବାଇଲ୍ ନମ୍ବର (WhatsApp Phone Number)",
      businessType: "ଆପଣ କେମିତି ବ୍ୟବସାୟ କରନ୍ତି? (Business Type)",
      smallshop: "ଛୋଟ ଦୋକାନ (Small Shop)",
      Wholesaler: "ଥୋକ ବ୍ୟବସାୟୀ (Wholesaler)",
      NewBusiness: "ନୂଆ ବ୍ୟବସାୟ (New Business)",
      Message: "ଆମକୁ ସଂପର୍କ କରିବାର ଅନ୍ୟ କାରଣ (Message)",
      Submit: "ସମର୍ପଣ କରନ୍ତୁ",
    },
  ];